Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version= "v20191014.0.0"
  config.vm.hostname = "development"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "development"
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end
  config.vm.provision "ansible_local" do |ansible|
     ansible.compatibility_mode = "2.0"
     ansible.playbook = "playbook-install-docker.yml"
  SHELL
end